build:
    environment:
        php:
            version: 7.0.8

    cache:
        directories:
            - ~/cphalcon

    dependencies:
        override:
            - composer install --prefer-source --no-interaction
        after: 
            - bin/install-phalcon.sh
            - php -r "echo \Phalcon\Version::get();"