language: php

php:
  - 5.5
  - 5.6

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/cphalcon

before_install:
  - composer install --prefer-source --no-interaction
  - bin/install-phalcon.sh

script:
  - vendor/bin/phpunit

notifications:
  email: false